excludes = [".envrc", ".gitignore", "LICENSE", "*.lock"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.ocaml]
command = "ocamlformat"
options = ["--inplace"]
includes = ["*.ml", "*.mli"]